"""Job taxonomy covering the whole Indian worker market — not just white-collar roles.

Deliberately spans every education level, from no formal schooling (daily wage, domestic,
agriculture) through skilled trades and ITI, to graduate and postgraduate professions.
Each sector carries the education level and wage basis typical for it, so the UI can
default sensibly and job seekers aren't shown fields that don't apply to them.
"""

# wage_basis: daily | monthly | annual | contract | piece_rate
# education: none | 8th | 10th | 12th | iti | diploma | graduate | pg
SECTORS = [
    {
        "key": "skilled_trades", "name": "Skilled Trades & Technicians", "icon": "tools",
        "education": "iti", "wage_basis": "daily", "blurb": "Electricians, plumbers, welders, mechanics",
        "roles": ["Electrician", "Plumber", "Welder", "Carpenter", "Painter", "Mason", "Fitter",
                  "AC & Refrigeration Technician", "Mobile Repair Technician", "Two-Wheeler Mechanic",
                  "Car Mechanic", "Lathe / CNC Operator", "Lift Technician", "Solar Panel Installer",
                  "Borewell Operator", "Tile Layer", "Fabricator", "Sheet Metal Worker", "Turner",
                  "Wireman", "Pump Operator", "Generator Technician"],
    },
    {
        "key": "daily_wage", "name": "Daily Wage & Construction", "icon": "hardhat",
        "education": "none", "wage_basis": "daily", "blurb": "Worker, helpers, loading, construction",
        "roles": ["Construction Worker", "Helper", "Loader / Unloader", "Mazdoor", "Road Worker",
                  "Building Cleaner", "Demolition Worker", "Scaffolder", "Concrete Mixer Operator",
                  "Site Watchman", "Earthwork Worker", "Packing Helper", "Warehouse Loader",
                  "Municipality Contract Worker", "Sanitation Worker", "Drainage Worker",
                  "Garbage Collection Staff", "Street Light Maintenance"],
    },
    {
        "key": "domestic", "name": "Domestic & Home Services", "icon": "home",
        "education": "none", "wage_basis": "monthly", "blurb": "Housekeeping, cooks, caretakers, nannies",
        "roles": ["House Maid", "Housekeeping Staff", "Home Cook", "Nanny / Babysitter",
                  "Elderly Caretaker", "Patient Attendant (Home)", "Gardener / Mali", "Watchman",
                  "Driver (Personal)", "Cleaner", "Dishwasher (Home)", "Laundry / Ironing Staff",
                  "Pet Caretaker", "Home Nurse", "Cook (Vegetarian)", "Cook (Non-Vegetarian)",
                  "Part-time Maid", "Live-in Caretaker"],
    },
    {
        "key": "hospitality", "name": "Hotels, Restaurants & Catering", "icon": "utensils",
        "education": "10th", "wage_basis": "monthly", "blurb": "Chefs, servers, hotel and restaurant staff",
        "roles": ["Chef", "Head Chef", "Sous Chef", "Commis Chef", "Tandoor Chef", "Chinese Chef",
                  "South Indian Cook", "Kitchen Helper", "Dishwasher", "Waiter / Server", "Bearer",
                  "Steward", "Captain", "Bartender", "Barista", "Hotel Receptionist", "Front Office Executive",
                  "Housekeeping Supervisor", "Room Attendant", "Laundry Staff", "Banquet Staff",
                  "Catering Staff", "Restaurant Manager", "Cashier", "Delivery Boy", "Food Packer",
                  "Bakery Assistant", "Sweet Shop Staff", "Juice Counter Staff"],
    },
    {
        "key": "healthcare", "name": "Hospital & Healthcare", "icon": "heart",
        "education": "12th", "wage_basis": "monthly", "blurb": "All hospital roles, clinical and support",
        "roles": ["Doctor (MBBS)", "Specialist Doctor", "Dentist", "Staff Nurse", "ANM / GNM Nurse",
                  "Ward Boy", "Ward Aaya", "Patient Attendant", "Lab Technician", "Radiographer",
                  "X-Ray Technician", "Pharmacist", "Physiotherapist", "Dialysis Technician",
                  "OT Technician", "ECG Technician", "Ambulance Driver", "Hospital Receptionist",
                  "Medical Records Clerk", "Hospital Housekeeping", "Biomedical Engineer",
                  "Optometrist", "Dietician", "Medical Representative", "Hospital Billing Executive",
                  "Hospital Administrator", "Medical Superintendent", "Duty Doctor", "Resident Doctor", "Consultant Physician", "General Surgeon", "Paediatrician", "Gynaecologist", "Orthopaedic Surgeon", "Cardiologist", "Dermatologist", "Psychiatrist", "Radiologist", "Anaesthetist", "Pathologist", "Ayurvedic Doctor", "Homeopathy Doctor", "Veterinary Doctor", "Dietitian", "Clinical Psychologist", "Medical Coder", "Insurance / TPA Executive", "Hospital Front Desk Executive", "Pharmacy Assistant"],
    },
    {
        "key": "agriculture", "name": "Agriculture & Rural", "icon": "leaf",
        "education": "none", "wage_basis": "daily", "blurb": "Farm work, dairy, poultry, rural trades",
        "roles": ["Farm Worker", "Tractor Driver", "Harvester Operator", "Irrigation Worker",
                  "Dairy Farm Worker", "Milkman", "Poultry Farm Worker", "Goat / Sheep Herder",
                  "Fish Farm Worker", "Plantation Worker", "Nursery Worker", "Horticulture Assistant",
                  "Pesticide Sprayer", "Seed Processing Worker", "Cold Storage Worker",
                  "Mandi / Market Helper", "Agri Equipment Mechanic", "Beekeeper", "Sericulture Worker",
                  "Agriculture Field Officer", "Veterinary Assistant",
                  "Agriculture Officer", "Farm Manager", "Agronomist", "Poultry Farm Supervisor", "Fisheries Assistant", "Tractor Operator", "Irrigation Technician", "Greenhouse Technician", "Seed Production Assistant", "Soil Testing Technician", "Mushroom Cultivation Worker", "Cold Storage Operator", "Farm Equipment Mechanic", "Agri Input Sales Executive", "Organic Farming Supervisor"],
    },
    {
        "key": "retail", "name": "Retail, Kirana & Sales", "icon": "store",
        "education": "10th", "wage_basis": "monthly", "blurb": "Shops, kirana stores, showrooms, field sales",
        "roles": ["Kirana Store Helper", "Shop Assistant", "Counter Salesman", "Cashier",
                  "Store Manager", "Showroom Executive", "Field Sales Executive", "Medical Store Assistant",
                  "Textile Shop Staff", "Jewellery Shop Staff", "Mobile Shop Salesman", "Stock Boy",
                  "Merchandiser", "Billing Operator", "Supermarket Staff", "Vegetable Vendor Assistant",
                  "Hardware Store Staff", "Petrol Pump Attendant", "Sales Officer", "Area Sales Manager"],
    },
    {
        "key": "logistics", "name": "Driving, Delivery & Logistics", "icon": "truck",
        "education": "8th", "wage_basis": "monthly", "blurb": "Drivers, delivery, warehouse, transport",
        "roles": ["Auto Driver", "Taxi / Cab Driver", "Truck Driver", "Heavy Vehicle Driver",
                  "Bus Driver", "Tempo Driver", "Delivery Executive", "Courier Boy", "Rider (Bike)",
                  "Warehouse Staff", "Packing Staff", "Inventory Assistant", "Forklift Operator",
                  "Logistics Coordinator", "Dispatch Clerk", "Loading Supervisor", "Fleet Supervisor",
                  "Warehouse Manager", "Warehouse Supervisor", "Inventory Executive", "Dispatch Executive", "Supply Chain Executive", "Fleet Manager", "Route Planner", "Last Mile Delivery Executive", "Courier Executive", "Freight Forwarding Executive", "Customs Clearance Executive", "Shipping Executive", "Import Export Executive", "Cold Chain Supervisor", "Packing Supervisor", "Material Handler", "Picker Packer", "Scanning Operator", "Hub Incharge"],
    },
    {
        "key": "security", "name": "Security & Facility", "icon": "shield",
        "education": "10th", "wage_basis": "monthly", "blurb": "Guards, supervisors, facility management",
        "roles": ["Security Guard", "Head Security Guard", "Gunman", "Bouncer", "CCTV Operator",
                  "Facility Supervisor", "Building Manager", "Society Caretaker", "Fire Safety Officer",
                  "Gatekeeper", "Parking Attendant"],
    },
    {
        "key": "manufacturing", "name": "Manufacturing & Factory", "icon": "factory",
        "education": "iti", "wage_basis": "monthly", "blurb": "Production, machine operation, quality",
        "roles": ["Machine Operator", "Production Helper", "Assembly Line Worker", "Quality Inspector",
                  "Packing Operator", "Boiler Operator", "Maintenance Technician", "Store Keeper",
                  "Production Supervisor", "Shift Incharge", "Tool Room Operator", "Textile Worker",
                  "Garment Tailor", "Embroidery Worker", "Printing Operator", "Plastic Moulding Operator",
                  "Food Processing Worker", "Chemical Plant Operator",
                  "Production Manager", "Plant Head", "Shift Supervisor", "Line Leader", "Maintenance Engineer", "Tool Room Technician", "CNC Programmer", "VMC Operator", "Press Operator", "Injection Moulding Operator", "Paint Shop Operator", "Dispatch Supervisor", "Industrial Engineer", "Safety Supervisor", "Production Planner", "Die Maker", "Foundry Worker", "Heat Treatment Operator"],
    },
    {
        "key": "it", "name": "IT & Software", "icon": "code",
        "education": "graduate", "wage_basis": "annual", "blurb": "Engineering, data, design, QA, support",
        "roles": ["Software Engineer", "Senior Software Engineer", "Full Stack Developer",
                  "Frontend Developer", "Backend Developer", "Mobile App Developer", "DevOps Engineer",
                  "Data Analyst", "Data Scientist", "ML Engineer", "QA / Test Engineer",
                  "Business Analyst", "Product Manager", "UI/UX Designer", "Cloud Engineer",
                  "Database Administrator", "Cybersecurity Analyst", "Technical Support Engineer",
                  "IT Helpdesk", "Network Engineer", "Scrum Master", "Solution Architect"],
    },
    {
        "key": "corporate", "name": "Corporate, Finance & Consulting", "icon": "briefcase",
        "education": "graduate", "wage_basis": "annual", "blurb": "Finance, HR, admin, consulting, insurance",
        "roles": ["Accountant", "Junior Accountant", "Tally Operator", "Chartered Accountant",
                  "Finance Manager", "Auditor", "HR Executive", "HR Manager", "Recruiter",
                  "Talent Acquisition Specialist", "Payroll Executive", "Admin Executive",
                  "Office Assistant", "Data Entry Operator", "Receptionist", "Back Office Executive",
                  "Customer Support Executive", "Tele Caller", "Insurance Advisor", "Insurance Agent",
                  "Loan Officer", "Bank Clerk", "Relationship Manager", "Management Consultant",
                  "Operations Manager", "Business Development Executive", "Digital Marketing Executive",
                  "Content Writer", "Graphic Designer", "Legal Advisor", "Company Secretary"],
    },
    {
        "key": "education", "name": "Education & Training", "icon": "cap",
        "education": "graduate", "wage_basis": "monthly", "blurb": "Teachers, trainers, school staff",
        "roles": ["School Teacher", "Primary Teacher", "Subject Teacher", "Lecturer", "Professor",
                  "Home Tutor", "Coaching Faculty", "Lab Assistant", "Librarian", "Physical Education Teacher",
                  "Anganwadi Worker", "Special Educator", "Training Coordinator", "Placement Officer",
                  "School Admin", "School Bus Driver", "Ayah / Attendant",
                  "School Principal", "Vice Principal", "TGT Teacher", "PGT Teacher", "Maths Teacher", "Science Teacher", "English Teacher", "Hindi Teacher", "Telugu Teacher", "Computer Teacher", "Pre-Primary Teacher", "Montessori Teacher", "College Lecturer", "Assistant Professor", "Associate Professor", "HOD", "Research Scholar", "Exam Coordinator", "Admission Counsellor", "Academic Coordinator", "Hostel Warden (School)", "School Bus Incharge", "Tutor", "Online Tutor", "Content Developer (Education)", "Curriculum Designer"],
    },
    {
        "key": "government", "name": "Government & Municipality", "icon": "building",
        "education": "10th", "wage_basis": "monthly", "blurb": "Municipal contracts, public works, civic roles",
        "roles": ["Municipality Contractor", "Contract Worker (Civic)", "Sanitary Supervisor",
                  "Water Works Operator", "Public Health Worker", "Field Surveyor", "Clerk",
                  "Peon / Attendant", "Data Entry (Government Scheme)", "ASHA Worker",
                  "Panchayat Assistant", "Revenue Assistant", "Forest Guard", "Home Guard"],
    },
    {
        "key": "beauty_events", "name": "Beauty, Events & Personal Services", "icon": "sparkle",
        "education": "none", "wage_basis": "monthly", "blurb": "Salon, tailoring, events, photography",
        "roles": ["Beautician", "Hair Stylist", "Barber", "Makeup Artist", "Spa Therapist",
                  "Massage Therapist", "Tailor", "Boutique Assistant", "Event Helper",
                  "Decorator", "Photographer", "Videographer", "DJ", "Wedding Planner Assistant",
                  "Mehendi Artist", "Fitness Trainer", "Yoga Instructor", "Swimming Coach"],
    },
    {
        "key": "bfsi", "name": "Banking, Finance & Insurance", "icon": "bank",
        "education": "graduate", "wage_basis": "monthly", "blurb": "Banks, NBFCs, insurance, microfinance",
        "roles": ["Bank Clerk", "Bank PO", "Branch Manager", "Loan Officer", "Credit Analyst",
                  "Collections Executive", "Recovery Agent", "Insurance Advisor", "Insurance Surveyor",
                  "Claims Executive", "Underwriter", "Actuarial Analyst", "Investment Advisor",
                  "Wealth Manager", "Mutual Fund Distributor", "Stock Broker", "Sub-Broker",
                  "Microfinance Field Officer", "Business Correspondent", "ATM Technician",
                  "Cashier (Bank)", "KYC Executive", "Risk Analyst", "Treasury Executive",
                  "Chartered Accountant", "Cost Accountant", "Tax Consultant", "GST Practitioner",
                  "Bookkeeper", "Accounts Payable Executive", "Payroll Executive", "Internal Auditor"],
    },
    {
        "key": "telecom", "name": "Telecom & Networking", "icon": "signal",
        "education": "iti", "wage_basis": "monthly", "blurb": "Towers, fibre, broadband, field engineering",
        "roles": ["Tower Technician", "Fibre Splicer", "Optical Fibre Technician", "Cable Puller",
                  "Broadband Installer", "DTH Installer", "Network Field Engineer", "RF Engineer",
                  "Transmission Engineer", "BTS Engineer", "Telecom Site Supervisor", "NOC Engineer",
                  "Telecom Sales Executive", "SIM Distributor", "Customer Care Executive (Telecom)"],
    },
    {
        "key": "energy", "name": "Power, Energy & Utilities", "icon": "bolt",
        "education": "iti", "wage_basis": "monthly", "blurb": "Power plants, solar, grid, water utilities",
        "roles": ["Lineman", "Substation Operator", "Power Plant Operator", "Turbine Technician",
                  "Boiler Attendant", "Electrical Supervisor", "Solar Installer", "Solar Site Engineer",
                  "Wind Turbine Technician", "Meter Reader", "Energy Auditor", "Grid Operator",
                  "Water Treatment Operator", "Pipeline Technician", "Gas Pipeline Fitter",
                  "LPG Delivery Staff", "Petrol Pump Manager", "Electrical Safety Officer"],
    },
    {
        "key": "automotive", "name": "Automotive & Workshop", "icon": "car",
        "education": "iti", "wage_basis": "monthly", "blurb": "Service centres, dealerships, EV, body shops",
        "roles": ["Automobile Technician", "Service Advisor", "Auto Electrician", "Denter", "Painter (Auto)",
                  "Wheel Alignment Technician", "Tyre Fitter", "EV Technician", "Battery Technician",
                  "Diesel Mechanic", "Bike Mechanic", "Workshop Supervisor", "Spare Parts In-charge",
                  "Vehicle Inspector", "Car Washer", "Driving Instructor", "Showroom Sales Consultant",
                  "Insurance Claims Coordinator (Auto)"],
    },
    {
        "key": "pharma", "name": "Pharma, Biotech & Life Sciences", "icon": "flask",
        "education": "graduate", "wage_basis": "monthly", "blurb": "Manufacturing, QA/QC, R&D, field",
        "roles": ["Production Chemist", "QA Executive", "QC Analyst", "Microbiologist",
                  "Regulatory Affairs Executive", "Formulation Scientist", "R&D Associate",
                  "Clinical Research Associate", "Pharmacovigilance Executive", "Medical Writer",
                  "Medical Representative", "Area Business Manager", "Packing Operator (Pharma)",
                  "Warehouse Executive (Pharma)", "Validation Engineer", "Bioinformatics Analyst",
                  "Area Sales Manager (Pharma)", "Packing Supervisor (Pharma)", "Store Officer (Pharma)", "Production Operator (Pharma)", "Granulation Operator", "Tablet Compression Operator", "Injectable Line Operator", "Cleanroom Technician", "Documentation Executive"],
    },
    {
        "key": "ecommerce", "name": "E-commerce, Startups & Gig Work", "icon": "cart",
        "education": "12th", "wage_basis": "monthly", "blurb": "Marketplaces, quick commerce, gig platforms",
        "roles": ["Warehouse Picker", "Packer", "Sorting Executive", "Last Mile Delivery Partner",
                  "Quick Commerce Rider", "Dark Store Associate", "Inventory Executive",
                  "Catalogue Executive", "Seller Support Executive", "Category Manager",
                  "Growth Marketer", "Performance Marketing Executive", "Community Manager",
                  "Customer Success Executive", "Operations Associate", "Field Verification Executive",
                  "Product Lister", "Order Processing Executive", "Returns Executive", "Marketplace Manager", "Customer Support Associate", "Warehouse Associate", "Packaging Associate", "Quality Check Associate", "Vendor Management Executive"],
    },
    {
        "key": "media", "name": "Media, Print & Entertainment", "icon": "camera",
        "education": "12th", "wage_basis": "monthly", "blurb": "News, film, printing, production, OTT",
        "roles": ["Journalist", "Sub Editor", "Content Writer", "Copywriter", "Proofreader",
                  "News Anchor", "Camera Operator", "Video Editor", "Sound Engineer", "Light Man",
                  "Spot Boy", "Production Assistant", "Set Designer", "Costume Assistant",
                  "Animator", "VFX Artist", "Motion Graphics Designer", "Radio Jockey",
                  "Printing Press Operator", "DTP Operator", "Screen Printer", "Bookbinder",
                  "Flex Board Designer", "Social Media Manager", "Podcast Producer"],
    },
    {
        "key": "legal", "name": "Legal & Compliance", "icon": "scale",
        "education": "graduate", "wage_basis": "monthly", "blurb": "Advocates, paralegal, compliance, courts",
        "roles": ["Advocate", "Junior Lawyer", "Legal Associate", "Paralegal", "Legal Clerk",
                  "Company Secretary", "Compliance Officer", "Contract Analyst", "Notary Assistant",
                  "Court Stenographer", "Typist (Legal)", "Document Verification Executive",
                  "Intellectual Property Analyst", "Worker Law Consultant"],
    },
    {
        "key": "realestate", "name": "Real Estate & Construction Management", "icon": "key",
        "education": "12th", "wage_basis": "monthly", "blurb": "Sales, site management, surveying, interiors",
        "roles": ["Real Estate Sales Executive", "Property Consultant", "Channel Partner Manager",
                  "Site Engineer", "Project Engineer", "Quantity Surveyor", "Estimation Engineer",
                  "Civil Supervisor", "Site Safety Officer", "Architect", "Draughtsman",
                  "Interior Designer", "Interior Site Supervisor", "Land Surveyor", "Valuer",
                  "Facility Manager", "Society Manager", "Leasing Executive"],
    },
    {
        "key": "travel", "name": "Travel, Tourism & Aviation", "icon": "plane",
        "education": "12th", "wage_basis": "monthly", "blurb": "Airlines, airports, travel agencies, guides",
        "roles": ["Cabin Crew", "Ground Staff", "Airport Loader", "Check-in Agent", "Ramp Agent",
                  "Aircraft Maintenance Technician", "Air Ticketing Executive", "Travel Consultant",
                  "Tour Operator", "Tour Guide", "Visa Executive", "Tourist Bus Driver",
                  "Hotel Reservation Executive", "Cruise Staff", "Adventure Sports Instructor",
                  "Airline Ground Staff", "Airport Customer Service Agent", "Baggage Handler", "Cargo Executive", "Railway Booking Clerk", "Bus Booking Executive", "Car Rental Executive", "Chauffeur", "Transport Coordinator"],
    },
    {
        "key": "transport_rail", "name": "Railways, Shipping & Ports", "icon": "ship",
        "education": "10th", "wage_basis": "monthly", "blurb": "Rail, ports, warehousing, freight, marine",
        "roles": ["Railway Technician", "Track Maintainer", "Loco Pilot Assistant", "Signal Technician",
                  "Station Cleaner", "Porter", "Freight Handler", "Crane Operator", "Port Worker",
                  "Container Handler", "Customs Clearance Executive", "Freight Forwarder",
                  "Shipping Coordinator", "Marine Engineer", "Deck Cadet", "Seafarer", "Fisherman",
                  "Boat Operator"],
    },
    {
        "key": "mining", "name": "Mining, Oil & Gas", "icon": "pickaxe",
        "education": "iti", "wage_basis": "monthly", "blurb": "Quarries, mines, rigs, refineries",
        "roles": ["Mine Worker", "Blaster", "Drill Operator", "Quarry Supervisor", "Mining Engineer",
                  "Geologist", "Surveyor (Mines)", "Heavy Earth Mover Operator", "Rig Operator",
                  "Refinery Operator", "Pipeline Inspector", "Safety Officer (Mines)",
                  "Explosives Handler", "Crusher Operator"],
    },
    {
        "key": "textiles", "name": "Textiles, Handicrafts & Artisans", "icon": "thread",
        "education": "none", "wage_basis": "piece_rate", "blurb": "Weaving, garments, crafts, cottage industry",
        "roles": ["Handloom Weaver", "Powerloom Operator", "Spinner", "Dyer", "Printer (Textile)",
                  "Garment Tailor", "Cutting Master", "Checker (Garments)", "Ironing Staff",
                  "Embroidery Artisan", "Zari Worker", "Block Printer", "Potter", "Basket Weaver",
                  "Leather Worker", "Cobbler", "Goldsmith", "Silversmith", "Bangle Maker",
                  "Carpet Weaver", "Wood Carver", "Stone Carver", "Toy Maker", "Candle Maker",
                  "Agarbatti Roller", "Papad Maker", "Pickle Maker"],
    },
    {
        "key": "food_processing", "name": "Food Processing & FMCG", "icon": "package",
        "education": "10th", "wage_basis": "monthly", "blurb": "Dairy, bakery, packaged foods, cold chain",
        "roles": ["Food Processing Operator", "Dairy Plant Operator", "Bakery Baker", "Confectioner",
                  "Butcher", "Meat Processor", "Fish Processor", "Cold Storage Attendant",
                  "Quality Checker (Food)", "Food Safety Officer", "FMCG Sales Representative",
                  "Distributor Sales Man", "Merchandiser (FMCG)", "Bottling Plant Operator",
                  "Flour Mill Operator", "Oil Mill Worker", "Sugar Mill Worker",
                  "Food Technologist", "Production Supervisor (Food)", "Quality Analyst (Food)", "Bakery Production Staff", "Dairy Processing Operator", "Meat Processing Worker", "Cold Storage Supervisor", "Packaging Line Operator", "Hygiene Supervisor", "FSSAI Compliance Executive", "Snacks Production Worker", "Spice Grinding Operator", "Oil Mill Operator", "Beverage Plant Operator"],
    },
    {
        "key": "sports_wellness", "name": "Sports, Fitness & Wellness", "icon": "run",
        "education": "12th", "wage_basis": "monthly", "blurb": "Gyms, coaching, therapy, yoga",
        "roles": ["Gym Trainer", "Personal Trainer", "Yoga Instructor", "Zumba Instructor",
                  "Sports Coach", "Cricket Coach", "Football Coach", "Swimming Instructor",
                  "Physiotherapist (Sports)", "Sports Nutritionist", "Umpire / Referee",
                  "Groundsman", "Sports Equipment Technician", "Ayurveda Therapist",
                  "Naturopathy Assistant", "Spa Manager"],
    },
    {
        "key": "social", "name": "NGO, Social Work & Development", "icon": "hands",
        "education": "graduate", "wage_basis": "monthly", "blurb": "NGOs, CSR, field programmes, community",
        "roles": ["Social Worker", "Field Coordinator", "Community Mobiliser", "Project Officer (NGO)",
                  "CSR Executive", "Fundraising Executive", "Grant Writer", "M&E Officer",
                  "Counsellor", "Child Protection Officer", "Rural Development Officer",
                  "SHG Coordinator", "Health Worker", "Sanitation Promoter", "Volunteer Coordinator"],
    },
    {
        "key": "defence", "name": "Defence, Police & Emergency", "icon": "badge",
        "education": "12th", "wage_basis": "monthly", "blurb": "Armed forces, police, fire, disaster response",
        "roles": ["Police Constable", "Head Constable", "Sub Inspector", "Home Guard",
                  "Fire Fighter", "Fire Safety Technician", "Disaster Response Volunteer",
                  "Ambulance Paramedic", "Emergency Dispatcher", "Ex-Serviceman Security Consultant",
                  "Armed Guard", "Prison Warder"],
    },
    {
        "key": "research", "name": "Research, Science & Academia", "icon": "microscope",
        "education": "pg", "wage_basis": "monthly", "blurb": "Labs, universities, think tanks, surveys",
        "roles": ["Research Assistant", "Research Associate", "Lab Technician (Research)",
                  "Data Collector", "Field Investigator", "Survey Enumerator", "Statistician",
                  "Scientist", "Junior Research Fellow", "Post-Doctoral Fellow", "Lab Manager",
                  "Scientific Officer", "Patent Analyst", "Academic Editor"],
    },
    {
        "key": "veterinary", "name": "Veterinary & Animal Care", "icon": "paw",
        "education": "12th", "wage_basis": "monthly", "blurb": "Vets, livestock, pet care, hatcheries",
        "roles": ["Veterinary Doctor", "Veterinary Assistant", "Livestock Supervisor",
                  "Artificial Insemination Technician", "Poultry Supervisor", "Hatchery Worker",
                  "Pet Groomer", "Pet Trainer", "Animal Shelter Attendant", "Cattle Feed Sales Executive",
                  "Fisheries Officer", "Dairy Extension Officer"],
    },
    {
        "key": "waste", "name": "Sanitation, Waste & Environment", "icon": "recycle",
        "education": "none", "wage_basis": "monthly", "blurb": "Waste management, recycling, environment",
        "roles": ["Waste Collector", "Segregation Worker", "Recycling Plant Operator",
                  "Composting Supervisor", "Sewage Treatment Operator", "Septic Tank Cleaner",
                  "Housekeeping Supervisor (Public)", "Pest Control Technician", "Fumigation Operator",
                  "Environment Officer", "EHS Executive", "Scrap Dealer Assistant"],
    },
    {
        "key": "religious", "name": "Community, Religious & Event Services", "icon": "bell",
        "education": "none", "wage_basis": "contract", "blurb": "Temples, functions, catering, community roles",
        "roles": ["Priest / Pandit", "Temple Attendant", "Caretaker (Religious Place)",
                  "Function Hall Manager", "Marriage Bureau Executive", "Band Musician",
                  "Dhol Player", "Cook (Bulk / Function)", "Serving Staff (Function)",
                  "Tent House Worker", "Flower Decorator", "Purohit Assistant", "Choir Member"],
    },

    # ==================== added: industries called out by the client ====================
    {
        "key": "hotels_resorts", "name": "Hotels, Resorts & PG", "icon": "bed",
        "education": "none", "wage_basis": "monthly", "blurb": "Hotels, lodges, hostels, PG accommodation",
        "roles": ["Hotel Manager", "Front Office Executive", "Receptionist", "Guest Relations Executive",
                  "Concierge", "Bell Boy", "Room Attendant", "Housekeeping Supervisor", "Laundry Attendant",
                  "Hostel Warden", "PG Caretaker", "PG Cook", "Hostel Mess Supervisor", "Resort Manager",
                  "Banquet Manager", "Banquet Server", "Reservation Executive", "Night Auditor",
                  "Lodge Attendant", "Duty Manager", "Housekeeping Room Boy", "Linen Room Attendant"],
    },
    {
        "key": "restaurants_bars", "name": "Restaurants, Bars & Cloud Kitchens", "icon": "utensils",
        "education": "none", "wage_basis": "monthly", "blurb": "Restaurants, pubs, bars, cloud kitchens, catering",
        "roles": ["Restaurant Manager", "Head Chef", "Sous Chef", "Chef de Partie", "Commis Chef",
                  "Tandoor Chef", "Chinese Chef", "South Indian Cook", "North Indian Cook", "Continental Chef",
                  "Pastry Chef", "Baker", "Kitchen Helper", "Dishwasher / Utility Staff", "Steward",
                  "Waiter / Server", "Captain", "Bartender", "Bar Manager", "Barista", "Sommelier",
                  "Pub Manager", "Bouncer", "Cloud Kitchen Manager", "Cloud Kitchen Cook",
                  "Food Packaging Staff", "Delivery Coordinator", "Billing Cashier", "Host / Hostess",
                  "Catering Supervisor", "Catering Helper", "Juice Counter Staff", "Chaat Counter Cook"],
    },
    {
        "key": "tourism", "name": "Tourism & Travel Services", "icon": "map",
        "education": "inter", "wage_basis": "monthly", "blurb": "Tour guides, travel desks, ticketing, holiday packages",
        "roles": ["Tour Guide", "Tour Manager", "Travel Consultant", "Travel Agent", "Ticketing Executive",
                  "Visa Executive", "Holiday Package Executive", "Tour Operator", "Adventure Sports Instructor",
                  "Trekking Guide", "Safari Guide", "Heritage Site Guide", "Tourist Information Officer",
                  "Destination Manager", "Travel Desk Executive", "Cruise Staff", "Tour Coordinator",
                  "Pilgrimage Tour Escort", "Homestay Manager"],
    },
    {
        "key": "heavy_vehicle", "name": "Heavy Vehicle & Driving", "icon": "truck",
        "education": "none", "wage_basis": "monthly", "blurb": "Truck, bus, crane, JCB, driving schools",
        "roles": ["Heavy Truck Driver", "Trailer Driver", "Container Driver", "Tanker Driver", "Bus Driver",
                  "School Bus Driver", "Tempo / LCV Driver", "Car Driver", "Taxi Driver", "Cab Driver",
                  "Auto Rickshaw Driver", "Ambulance Driver", "Tipper Driver", "JCB Operator",
                  "Excavator Operator", "Crane Operator", "Forklift Operator", "Bulldozer Operator",
                  "Road Roller Operator", "Tractor Driver", "Driving Instructor", "Driving School Manager",
                  "Fleet Supervisor", "Transport Incharge", "Vehicle Cleaner", "Conductor"],
    },
    {
        "key": "coal_cement", "name": "Coal, Cement & Heavy Industry", "icon": "mountain",
        "education": "iti", "wage_basis": "monthly", "blurb": "Coal mining, cement plants, quarry, heavy plant",
        "roles": ["Coal Mine Worker", "Coal Mine Supervisor", "Mining Engineer", "Mine Surveyor",
                  "Blasting Operator", "Drill Operator", "Shot Firer", "Underground Mine Worker",
                  "Cement Plant Operator", "Kiln Operator", "Raw Mill Operator", "Packing Plant Operator",
                  "Cement Loader", "Quarry Supervisor", "Crusher Operator", "Conveyor Operator",
                  "Plant Maintenance Fitter", "Plant Electrician", "Weighbridge Operator",
                  "Mine Safety Officer", "Geologist", "Batching Plant Operator", "Concrete Pump Operator"],
    },
    {
        "key": "paramedical", "name": "Nursing, Paramedical & Lab", "icon": "stethoscope",
        "education": "diploma", "wage_basis": "monthly", "blurb": "Nursing, MLT/DMLT, technicians, allied health",
        "roles": ["Staff Nurse", "ANM Nurse", "GNM Nurse", "B.Sc Nursing", "ICU Nurse", "OT Nurse",
                  "Nursing Superintendent", "Ward Boy", "Ward Aaya", "Nursing Assistant",
                  "Medical Lab Technician (MLT)", "DMLT Technician", "Pathology Lab Technician",
                  "Blood Bank Technician", "Phlebotomist", "Sample Collection Executive",
                  "Radiology Technician", "X-Ray Technician", "CT Scan Technician", "MRI Technician",
                  "Ultrasound Technician", "ECG Technician", "Dialysis Technician", "OT Technician",
                  "Anaesthesia Technician", "Physiotherapist", "Occupational Therapist",
                  "Speech Therapist", "Optometrist", "Dental Hygienist", "Dental Assistant",
                  "Emergency Medical Technician (EMT)", "Paramedic", "Ambulance Technician",
                  "Home Care Nurse", "Patient Attendant", "Hospital Housekeeping Staff",
                  "Medical Records Technician", "CSSD Technician", "Perfusionist", "Audiologist"],
    },
    {
        "key": "chemical_battery", "name": "Chemical, Battery & Process Plants", "icon": "flask",
        "education": "diploma", "wage_basis": "monthly", "blurb": "Chemical plants, battery manufacturing, refineries",
        "roles": ["Chemical Plant Operator", "Process Operator", "Shift Incharge", "Chemical Engineer",
                  "Battery Assembly Operator", "Cell Manufacturing Technician", "Battery Testing Technician",
                  "Lithium Cell Line Operator", "Battery Pack Assembler", "BMS Test Engineer",
                  "Electrode Coating Operator", "Formation & Grading Operator", "Boiler Operator",
                  "Reactor Operator", "Distillation Operator", "Effluent Treatment Plant Operator",
                  "Lab Chemist", "Quality Control Chemist", "R&D Chemist", "Safety Officer (Chemical)",
                  "Instrumentation Technician", "Utility Operator", "Blending Operator", "Packing Operator"],
    },
    {
        "key": "cinema_theatre", "name": "Cinema, Theatre & Live Events", "icon": "film",
        "education": "none", "wage_basis": "monthly", "blurb": "Movie theatres, multiplexes, concession counters",
        "roles": ["Theatre Manager", "Multiplex Manager", "Box Office Executive", "Ticket Counter Staff",
                  "Usher", "Gate Keeper", "Projectionist", "Digital Cinema Technician", "Sound Technician",
                  "Screen Cleaning Staff", "Concession Counter Staff", "Popcorn Counter Staff",
                  "Snacks Seller", "Beverage Counter Staff", "Food Court Attendant", "Candy Bar Attendant",
                  "Theatre Security Guard", "Parking Attendant", "Show Coordinator",
                  "Event Stage Hand", "Lighting Technician", "Live Event Crew"],
    },
    {
        "key": "kirana_stores", "name": "Kirana & General Stores", "icon": "store",
        "education": "none", "wage_basis": "monthly", "blurb": "Kirana shops, general stores, supermarkets",
        "roles": ["Kirana Store Helper", "Store Salesman", "Counter Salesman", "Billing Operator",
                  "Cashier", "Stock Boy", "Shelf Stacker", "Home Delivery Boy", "Store Supervisor",
                  "General Store Manager", "Supermarket Floor Staff", "Vegetable Counter Staff",
                  "Dairy Counter Staff", "Provision Store Incharge", "Purchase Assistant",
                  "Godown Keeper", "Inventory Clerk", "Weighing Staff", "Loading Helper"],
    },
]

# Flat lookups used by search filters and AI prompts.
ALL_ROLES = sorted({r for s in SECTORS for r in s["roles"]})
SECTOR_KEYS = [s["key"] for s in SECTORS]

EDUCATION_LEVELS = [
    {"key": "none", "label": "No formal education required"},
    {"key": "8th", "label": "8th pass"},
    {"key": "10th", "label": "10th pass"},
    {"key": "12th", "label": "12th / Intermediate"},
    {"key": "iti", "label": "ITI / Certificate"},
    {"key": "diploma", "label": "Diploma"},
    {"key": "graduate", "label": "Graduate"},
    {"key": "pg", "label": "Post Graduate"},
]

WAGE_BASIS = [
    {"key": "daily", "label": "Daily wage"},
    {"key": "weekly", "label": "Weekly"},
    {"key": "monthly", "label": "Monthly salary"},
    {"key": "annual", "label": "Annual (LPA)"},
    {"key": "contract", "label": "Contract / project"},
    {"key": "piece_rate", "label": "Piece rate"},
]

JOB_TYPES = [
    {"key": "full_time", "label": "Full time"},
    {"key": "part_time", "label": "Part time"},
    {"key": "daily", "label": "Daily / casual"},
    {"key": "contract", "label": "Contract"},
    {"key": "temporary", "label": "Temporary / seasonal"},
    {"key": "apprentice", "label": "Apprentice / trainee"},
    {"key": "wfh", "label": "Work from home"},
]


def sector_for_role(role: str) -> dict | None:
    r = (role or "").strip().lower()
    for s in SECTORS:
        if any(r == x.lower() for x in s["roles"]):
            return s
    for s in SECTORS:   # partial match fallback
        if any(r in x.lower() or x.lower() in r for x in s["roles"] if r):
            return s
    return None


def taxonomy_payload() -> dict:
    return {
        "sectors": [{k: v for k, v in s.items()} for s in SECTORS],
        "education_levels": EDUCATION_LEVELS,
        "wage_basis": WAGE_BASIS,
        "job_types": JOB_TYPES,
        "role_count": len(ALL_ROLES),
    }

# ============================================================================
#  Skills library — organised by sector so the UI can show only what fits.
# ============================================================================
SKILLS_BY_SECTOR = {
    "hotels_resorts": ["Front Office", "Guest Handling", "Housekeeping", "Opera PMS", "Reservations",
        "Banquet Operations", "Room Service", "Laundry Management", "Hostel Administration",
        "Inventory Control", "Complaint Handling", "Billing", "Hospitality Etiquette"],
    "restaurants_bars": ["Food Preparation", "Indian Cuisine", "Chinese Cuisine", "Continental Cuisine",
        "Tandoor", "Baking", "Pastry", "Food Plating", "Menu Planning", "Kitchen Hygiene", "HACCP",
        "Bartending", "Cocktail Mixing", "POS Billing", "Table Service", "Order Taking",
        "Food Costing", "Cloud Kitchen Operations", "Food Packaging", "Customer Service"],
    "tourism": ["Tour Planning", "Itinerary Design", "Ticketing", "GDS / Amadeus", "Visa Processing",
        "Customer Handling", "Local History Knowledge", "Multilingual Communication", "Group Handling",
        "Adventure Safety", "First Aid", "Negotiation", "Travel Documentation"],
    "heavy_vehicle": ["Heavy Vehicle Licence", "LMV Licence", "Defensive Driving", "Route Knowledge",
        "Vehicle Maintenance", "Load Securing", "GPS Navigation", "Log Book Maintenance",
        "Crane Operation", "JCB Operation", "Forklift Operation", "Road Safety", "Trip Sheet"],
    "coal_cement": ["Mine Safety", "Blasting", "Drilling", "Kiln Operation", "Crusher Operation",
        "Conveyor Maintenance", "Heavy Equipment Operation", "DGMS Regulations", "Survey",
        "Batching Plant", "Quality Testing", "Dust Control", "Shift Operations"],
    "paramedical": ["Patient Care", "Vitals Monitoring", "Injection Administration", "IV Cannulation",
        "Wound Dressing", "Sample Collection", "Phlebotomy", "Blood Grouping", "Haematology",
        "Biochemistry", "Microbiology", "Histopathology", "Lab Equipment Handling", "Radiography",
        "CT / MRI Operation", "ECG", "Dialysis", "OT Assistance", "Sterilisation", "BLS / ACLS",
        "Infection Control", "Medical Records", "HMIS", "Physiotherapy Techniques"],
    "chemical_battery": ["Process Control", "DCS Operation", "Reactor Handling", "Distillation",
        "Boiler Operation", "ETP Operation", "Titration", "HPLC", "GC", "Spectrophotometry",
        "Cell Assembly", "Battery Testing", "BMS", "Electrode Coating", "Cleanroom Practice",
        "Chemical Safety", "MSDS", "GMP", "Quality Control"],
    "cinema_theatre": ["Ticketing Systems", "Cash Handling", "Crowd Management", "Digital Projection",
        "Dolby Sound", "Customer Service", "Concession Sales", "Upselling", "Inventory Handling",
        "Food Handling", "Show Scheduling", "Stage Lighting", "AV Setup"],
    "kirana_stores": ["Billing", "POS Operation", "Cash Handling", "Stock Management", "Shelf Arrangement",
        "Weighing", "Customer Service", "Order Taking", "Home Delivery", "Vendor Coordination",
        "Expiry Management", "Basic Accounts", "UPI Payments"],
    "it": [
        "Python",
        "Java",
        "JavaScript",
        "TypeScript",
        "C",
        "C++",
        "C#",
        "Go",
        "Rust",
        "Ruby",
        "PHP",
        "Swift",
        "Kotlin",
        "Scala",
        "Perl",
        "R",
        "MATLAB",
        "Dart",
        "Objective-C",
        "VB.NET",
        "COBOL",
        "Shell Scripting",
        "PowerShell",
        "Bash",
        "React",
        "Angular",
        "Vue.js",
        "Next.js",
        "Svelte",
        "jQuery",
        "HTML5",
        "CSS3",
        "Tailwind CSS",
        "Bootstrap",
        "SASS",
        "Redux",
        "Webpack",
        "Vite",
        "Node.js",
        "Express.js",
        "Django",
        "Flask",
        "FastAPI",
        "Spring Boot",
        "Laravel",
        "Ruby on Rails",
        ".NET Core",
        "ASP.NET",
        "Hibernate",
        "GraphQL",
        "REST API",
        "gRPC",
        "Microservices",
        "MySQL",
        "PostgreSQL",
        "MongoDB",
        "Oracle",
        "SQL Server",
        "Redis",
        "Cassandra",
        "DynamoDB",
        "Elasticsearch",
        "Neo4j",
        "SQLite",
        "MariaDB",
        "Snowflake",
        "BigQuery",
        "Redshift",
        "AWS",
        "Azure",
        "Google Cloud",
        "Docker",
        "Kubernetes",
        "Terraform",
        "Ansible",
        "Jenkins",
        "GitLab CI",
        "GitHub Actions",
        "CircleCI",
        "Prometheus",
        "Grafana",
        "Datadog",
        "Nginx",
        "Apache",
        "Linux Administration",
        "Windows Server",
        "VMware",
        "Machine Learning",
        "Deep Learning",
        "TensorFlow",
        "PyTorch",
        "Scikit-learn",
        "Keras",
        "NLP",
        "Computer Vision",
        "Pandas",
        "NumPy",
        "Spark",
        "Hadoop",
        "Kafka",
        "Airflow",
        "dbt",
        "Tableau",
        "Power BI",
        "Looker",
        "Data Modelling",
        "ETL",
        "Data Warehousing",
        "Manual Testing",
        "Automation Testing",
        "Selenium",
        "Cypress",
        "Playwright",
        "JUnit",
        "TestNG",
        "Appium",
        "JMeter",
        "Postman",
        "API Testing",
        "Performance Testing",
        "Security Testing",
        "Test Planning",
        "Android Development",
        "iOS Development",
        "React Native",
        "Flutter",
        "Xamarin",
        "Ionic",
        "Git",
        "Jira",
        "Confluence",
        "Agile",
        "Scrum",
        "Kanban",
        "SAFe",
        "SDLC",
        "System Design",
        "OOP",
        "Data Structures",
        "Algorithms",
        "Design Patterns",
        "Cybersecurity",
        "Penetration Testing",
        "SIEM",
        "Firewall Management",
        "Network Security",
        "Ethical Hacking",
        "IAM",
        "Cryptography",
        "SOC Operations",
        "Vulnerability Assessment",
        "ISO 27001",
        "Salesforce",
        "SAP ABAP",
        "SAP MM",
        "SAP FICO",
        "SAP HANA",
        "ServiceNow",
        "Workday",
        "Dynamics 365",
        "Sharepoint",
        "Power Apps",
        "UiPath",
        "Blue Prism",
        "RPA",
        "Blockchain",
        "Solidity",
        "Web3",
        "AR/VR",
        "Unity",
        "Unreal Engine",
        "Technical Support",
        "Helpdesk",
        "Active Directory",
        "Troubleshooting",
        "Hardware Repair",
        "Networking",
        "CCNA",
        "Routing & Switching",
        "VoIP",
        "LAN/WAN",
        "Server Maintenance"
    ],
    "skilled_trades": [
        "House Wiring",
        "Industrial Wiring",
        "Panel Wiring",
        "Motor Rewinding",
        "Transformer Maintenance",
        "Circuit Testing",
        "Earthing",
        "Cable Jointing",
        "Switchgear",
        "Inverter Repair",
        "UPS Repair",
        "Generator Servicing",
        "Pipe Fitting",
        "Pipe Threading",
        "Leak Detection",
        "Sanitary Fitting",
        "Drainage Work",
        "Water Tank Installation",
        "Bathroom Fitting",
        "PVC Welding",
        "Solvent Welding",
        "Arc Welding",
        "MIG Welding",
        "TIG Welding",
        "Gas Welding",
        "Spot Welding",
        "Brazing",
        "Soldering",
        "Metal Cutting",
        "Grinding",
        "Sheet Metal Work",
        "Fabrication",
        "Blueprint Reading",
        "Carpentry",
        "Wood Turning",
        "Furniture Making",
        "Door Fitting",
        "Modular Kitchen Fitting",
        "Polishing",
        "Laminate Work",
        "Masonry",
        "Bricklaying",
        "Plastering",
        "Concrete Mixing",
        "Tile Laying",
        "Marble Fitting",
        "Waterproofing",
        "Shuttering",
        "Bar Bending",
        "Painting",
        "Spray Painting",
        "Putty Work",
        "Wall Texturing",
        "POP Work",
        "False Ceiling",
        "AC Installation",
        "AC Servicing",
        "Refrigeration Repair",
        "Compressor Repair",
        "Gas Charging",
        "Chiller Maintenance",
        "Lathe Operation",
        "Milling",
        "CNC Programming",
        "VMC Operation",
        "Drilling",
        "Boring",
        "Tool Grinding",
        "Die Making",
        "Press Operation",
        "Hydraulics",
        "Pneumatics",
        "PLC Programming",
        "SCADA",
        "Instrumentation",
        "Calibration",
        "Mobile Repair",
        "Laptop Repair",
        "TV Repair",
        "Washing Machine Repair",
        "Home Appliance Repair",
        "Electronics Assembly",
        "PCB Soldering",
        "Solar Panel Installation",
        "Borewell Operation",
        "Lift Maintenance",
        "Crane Operation",
        "Forklift Operation",
        "Scaffolding",
        "Rigging"
    ],
    "healthcare": [
        "Patient Care",
        "Vital Signs Monitoring",
        "Injection Administration",
        "IV Cannulation",
        "Wound Dressing",
        "Catheterisation",
        "Oxygen Therapy",
        "Nebulisation",
        "CPR",
        "First Aid",
        "Basic Life Support",
        "Advanced Cardiac Life Support",
        "ICU Care",
        "NICU Care",
        "Emergency Care",
        "Post-operative Care",
        "Palliative Care",
        "Geriatric Care",
        "Paediatric Care",
        "Maternity Care",
        "Home Nursing",
        "Bedside Assistance",
        "Phlebotomy",
        "Blood Sampling",
        "Sample Collection",
        "Pathology Testing",
        "Biochemistry Analysis",
        "Haematology",
        "Microbiology",
        "Histopathology",
        "Blood Banking",
        "X-Ray Operation",
        "CT Scan",
        "MRI Operation",
        "Ultrasound",
        "ECG",
        "EEG",
        "Dialysis",
        "Ventilator Operation",
        "OT Assistance",
        "Sterilisation",
        "Autoclaving",
        "CSSD",
        "Pharmacy Dispensing",
        "Drug Inventory",
        "Prescription Handling",
        "Medical Billing",
        "Hospital Administration",
        "Medical Records",
        "Insurance Claims",
        "TPA Coordination",
        "Patient Registration",
        "Appointment Scheduling",
        "Physiotherapy",
        "Occupational Therapy",
        "Speech Therapy",
        "Rehabilitation",
        "Nutrition Counselling",
        "Diet Planning",
        "Vaccination",
        "Immunisation",
        "Infection Control",
        "Biomedical Waste Management",
        "Hospital Housekeeping",
        "Ambulance Operation",
        "Triage"
    ],
    "hospitality": [
        "Indian Cooking",
        "North Indian Cuisine",
        "South Indian Cuisine",
        "Chinese Cuisine",
        "Continental Cuisine",
        "Italian Cuisine",
        "Mughlai Cuisine",
        "Tandoor",
        "Grilling",
        "Baking",
        "Pastry",
        "Confectionery",
        "Bakery Production",
        "Chaat Preparation",
        "Biryani Preparation",
        "Sweet Making",
        "Menu Planning",
        "Food Costing",
        "Portion Control",
        "Kitchen Management",
        "Food Safety",
        "HACCP",
        "FSSAI Compliance",
        "Hygiene Standards",
        "Inventory Management",
        "Stock Rotation",
        "Vendor Management",
        "Table Service",
        "Silver Service",
        "Buffet Service",
        "Room Service",
        "Order Taking",
        "Billing",
        "POS Operation",
        "Upselling",
        "Wine Service",
        "Bartending",
        "Cocktail Making",
        "Coffee Brewing",
        "Barista Skills",
        "Latte Art",
        "Front Office",
        "Guest Relations",
        "Check-in / Check-out",
        "Reservation Handling",
        "Concierge Service",
        "Complaint Handling",
        "Housekeeping",
        "Room Cleaning",
        "Laundry Operations",
        "Linen Management",
        "Banquet Setup",
        "Event Coordination",
        "Catering Operations",
        "Food Delivery",
        "Packaging"
    ],
    "agriculture": [
        "Ploughing",
        "Sowing",
        "Transplanting",
        "Weeding",
        "Harvesting",
        "Threshing",
        "Irrigation",
        "Drip Irrigation",
        "Sprinkler Systems",
        "Fertiliser Application",
        "Pesticide Spraying",
        "Organic Farming",
        "Vermicomposting",
        "Soil Testing",
        "Seed Treatment",
        "Nursery Management",
        "Grafting",
        "Pruning",
        "Greenhouse Management",
        "Hydroponics",
        "Tractor Operation",
        "Harvester Operation",
        "Rotavator Operation",
        "Farm Equipment Maintenance",
        "Pump Operation",
        "Dairy Farming",
        "Milking",
        "Cattle Feeding",
        "Cattle Health Care",
        "Artificial Insemination",
        "Poultry Farming",
        "Hatchery Operations",
        "Goat Rearing",
        "Sheep Rearing",
        "Fish Farming",
        "Aquaculture",
        "Shrimp Farming",
        "Beekeeping",
        "Sericulture",
        "Mushroom Cultivation",
        "Crop Planning",
        "Post-harvest Handling",
        "Grading & Sorting",
        "Cold Storage",
        "Warehouse Management",
        "Mandi Operations",
        "Agri Marketing",
        "Farm Record Keeping"
    ],
    "corporate": [
        "Tally ERP",
        "Tally Prime",
        "Busy Accounting",
        "QuickBooks",
        "Zoho Books",
        "SAP FICO",
        "Bookkeeping",
        "Journal Entries",
        "Bank Reconciliation",
        "Accounts Payable",
        "Accounts Receivable",
        "GST Filing",
        "TDS Filing",
        "Income Tax Return",
        "Payroll Processing",
        "PF & ESI",
        "Statutory Compliance",
        "Auditing",
        "Internal Audit",
        "Financial Reporting",
        "Balance Sheet",
        "P&L Analysis",
        "Budgeting",
        "Forecasting",
        "Cost Accounting",
        "Working Capital Management",
        "Financial Modelling",
        "Valuation",
        "Recruitment",
        "Talent Acquisition",
        "Sourcing",
        "Screening",
        "Interviewing",
        "Onboarding",
        "HR Operations",
        "HRMS",
        "Employee Engagement",
        "Performance Management",
        "Appraisal",
        "Training & Development",
        "Exit Formalities",
        "Labour Law",
        "Industrial Relations",
        "Compensation & Benefits",
        "HR Analytics",
        "MS Excel",
        "Advanced Excel",
        "Pivot Tables",
        "VLOOKUP",
        "Macros",
        "MS Word",
        "MS PowerPoint",
        "MS Outlook",
        "Google Workspace",
        "Data Entry",
        "Typing",
        "Documentation",
        "Report Writing",
        "Minutes of Meeting",
        "Calendar Management",
        "Travel Coordination",
        "Vendor Coordination",
        "Office Administration",
        "Front Desk",
        "Telephone Handling",
        "Business Development",
        "Lead Generation",
        "Cold Calling",
        "Client Relationship",
        "Account Management",
        "Negotiation",
        "Proposal Writing",
        "Tender Management",
        "CRM",
        "Salesforce CRM",
        "Zoho CRM",
        "Sales Forecasting",
        "Target Achievement",
        "Channel Sales",
        "B2B Sales",
        "B2C Sales",
        "Retail Sales",
        "Institutional Sales",
        "Digital Marketing",
        "SEO",
        "SEM",
        "Google Ads",
        "Meta Ads",
        "Social Media Marketing",
        "Content Marketing",
        "Email Marketing",
        "Copywriting",
        "Brand Management",
        "Market Research",
        "Campaign Management",
        "Google Analytics",
        "Influencer Marketing",
        "Project Management",
        "Stakeholder Management",
        "Risk Management",
        "Process Improvement",
        "Six Sigma",
        "Lean",
        "Operations Management",
        "Supply Chain",
        "Procurement",
        "Vendor Negotiation",
        "Logistics Coordination",
        "Inventory Control"
    ],
    "manufacturing": [
        "Production Planning",
        "Assembly Line Operation",
        "Machine Operation",
        "Quality Control",
        "Quality Assurance",
        "In-process Inspection",
        "Final Inspection",
        "Vernier Caliper",
        "Micrometer",
        "Gauge Reading",
        "Drawing Reading",
        "GD&T",
        "SPC",
        "Root Cause Analysis",
        "5S",
        "Kaizen",
        "TPM",
        "Poka-Yoke",
        "Six Sigma",
        "ISO 9001",
        "Injection Moulding",
        "Blow Moulding",
        "Extrusion",
        "Die Casting",
        "Forging",
        "Heat Treatment",
        "Powder Coating",
        "Electroplating",
        "Anodising",
        "Surface Finishing",
        "Packaging Operations",
        "Labelling",
        "Batch Coding",
        "Boiler Operation",
        "Chemical Handling",
        "Process Control",
        "DCS Operation",
        "Utility Maintenance",
        "Preventive Maintenance",
        "Breakdown Maintenance",
        "Predictive Maintenance",
        "Lubrication",
        "Safety Compliance",
        "PPE Usage",
        "Fire Safety",
        "Hazard Identification",
        "Work Permit System",
        "Textile Weaving",
        "Spinning",
        "Dyeing",
        "Printing",
        "Garment Stitching",
        "Pattern Making",
        "Cutting",
        "Fabric Inspection",
        "Embroidery",
        "Quality Checking"
    ],
    "logistics": [
        "LMV Driving",
        "HMV Driving",
        "Heavy Vehicle Driving",
        "Two-Wheeler Riding",
        "Defensive Driving",
        "Route Planning",
        "GPS Navigation",
        "Vehicle Maintenance",
        "Trip Sheet Management",
        "Fuel Management",
        "Log Book Maintenance",
        "Warehouse Operations",
        "Inventory Management",
        "Stock Auditing",
        "Picking & Packing",
        "Dispatch",
        "Loading & Unloading",
        "Forklift Operation",
        "Pallet Handling",
        "Barcode Scanning",
        "WMS",
        "Order Fulfilment",
        "Last Mile Delivery",
        "Cash on Delivery Handling",
        "Reverse Logistics",
        "Freight Forwarding",
        "Customs Documentation",
        "Export Documentation",
        "Import Documentation",
        "Bill of Lading",
        "E-way Bill",
        "Fleet Management",
        "Transport Coordination",
        "Supply Chain Planning"
    ],
    "retail": [
        "Customer Service",
        "Counter Sales",
        "Product Demonstration",
        "Visual Merchandising",
        "Shelf Stocking",
        "Planogram",
        "Billing",
        "POS Operation",
        "Cash Handling",
        "Card Payments",
        "UPI Payments",
        "Store Operations",
        "Stock Management",
        "Shrinkage Control",
        "Loss Prevention",
        "Store Opening & Closing",
        "Inventory Audit",
        "Vendor Coordination",
        "Category Management",
        "Pricing",
        "Promotions",
        "Loyalty Programs",
        "Complaint Resolution",
        "Upselling",
        "Cross-selling",
        "Footfall Analysis",
        "Sales Reporting"
    ],
    "security": [
        "Access Control",
        "Visitor Management",
        "Patrolling",
        "CCTV Monitoring",
        "Surveillance",
        "Alarm Systems",
        "Fire Fighting",
        "Emergency Response",
        "Evacuation Procedures",
        "Incident Reporting",
        "Frisking",
        "Baggage Screening",
        "Metal Detector Operation",
        "Crowd Control",
        "VIP Protection",
        "Gate Management",
        "Key Management",
        "Shift Handover",
        "Security Documentation",
        "Unarmed Combat",
        "Disaster Management"
    ],
    "education": [
        "Lesson Planning",
        "Curriculum Development",
        "Classroom Management",
        "Subject Teaching",
        "Mathematics Teaching",
        "Science Teaching",
        "English Teaching",
        "Social Studies Teaching",
        "Computer Teaching",
        "Special Education",
        "Child Psychology",
        "Student Counselling",
        "Assessment & Evaluation",
        "Question Paper Setting",
        "Answer Sheet Evaluation",
        "Parent Communication",
        "Smart Board Usage",
        "E-learning",
        "Online Teaching",
        "LMS Administration",
        "Library Management",
        "Lab Management",
        "Sports Coaching",
        "Extra-curricular Coordination",
        "Admission Counselling",
        "Placement Coordination"
    ],
    "domestic": [
        "House Cleaning",
        "Sweeping & Mopping",
        "Dusting",
        "Utensil Cleaning",
        "Washing Clothes",
        "Ironing",
        "Cooking",
        "Meal Preparation",
        "Grocery Shopping",
        "Child Care",
        "Infant Care",
        "Elderly Care",
        "Bedridden Patient Care",
        "Medicine Reminders",
        "Companionship",
        "Pet Care",
        "Dog Walking",
        "Gardening",
        "Plant Care",
        "Driving",
        "Car Cleaning",
        "Home Organisation",
        "Basic First Aid"
    ],
    "beauty_events": [
        "Hair Cutting",
        "Hair Styling",
        "Hair Colouring",
        "Hair Spa",
        "Keratin Treatment",
        "Facial",
        "Clean-up",
        "Bleaching",
        "Threading",
        "Waxing",
        "Manicure",
        "Pedicure",
        "Nail Art",
        "Bridal Makeup",
        "Party Makeup",
        "HD Makeup",
        "Airbrush Makeup",
        "Mehendi Design",
        "Saree Draping",
        "Massage Therapy",
        "Spa Treatments",
        "Aromatherapy",
        "Tailoring",
        "Stitching",
        "Blouse Designing",
        "Alteration",
        "Pattern Cutting",
        "Embroidery",
        "Aari Work",
        "Event Planning",
        "Stage Decoration",
        "Flower Decoration",
        "Balloon Decoration",
        "Lighting Setup",
        "Sound Setup",
        "Photography",
        "Videography",
        "Photo Editing",
        "Video Editing",
        "Drone Operation",
        "Album Designing"
    ],
    "bfsi": [
        "Loan Processing",
        "Credit Appraisal",
        "Credit Underwriting",
        "KYC Verification",
        "AML Compliance",
        "Document Verification",
        "Field Investigation",
        "Collections",
        "Recovery",
        "NPA Management",
        "Cash Management",
        "Cheque Clearing",
        "Account Opening",
        "Fixed Deposits",
        "Locker Operations",
        "Core Banking",
        "Finacle",
        "Flexcube",
        "Insurance Underwriting",
        "Policy Servicing",
        "Claims Processing",
        "Claim Settlement",
        "Risk Assessment",
        "Actuarial Analysis",
        "Reinsurance",
        "Motor Insurance",
        "Health Insurance",
        "Life Insurance",
        "General Insurance",
        "Surveying & Loss Assessment",
        "Mutual Funds",
        "Equity Research",
        "Technical Analysis",
        "Fundamental Analysis",
        "Portfolio Management",
        "Wealth Management",
        "Financial Planning",
        "Demat Operations",
        "Trading Terminal",
        "NISM Certification",
        "Treasury Operations",
        "Forex"
    ],
    "media": [
        "News Writing",
        "Feature Writing",
        "Editing",
        "Proofreading",
        "Sub-editing",
        "Headline Writing",
        "Interviewing",
        "Reporting",
        "Anchoring",
        "Voice Over",
        "Script Writing",
        "Screenplay",
        "Story Boarding",
        "Content Strategy",
        "Blogging",
        "Camera Operation",
        "Cinematography",
        "Lighting",
        "Sound Recording",
        "Boom Operation",
        "Video Editing",
        "Premiere Pro",
        "Final Cut Pro",
        "DaVinci Resolve",
        "After Effects",
        "Motion Graphics",
        "2D Animation",
        "3D Animation",
        "Maya",
        "Blender",
        "VFX",
        "Colour Grading",
        "Photoshop",
        "Illustrator",
        "InDesign",
        "CorelDRAW",
        "Canva",
        "Figma",
        "UI Design",
        "UX Research",
        "Graphic Design",
        "Logo Design",
        "Print Design",
        "DTP",
        "Offset Printing",
        "Screen Printing",
        "Flex Printing",
        "Bookbinding"
    ],
    "telecom": [
        "Fibre Splicing",
        "OTDR Testing",
        "Cable Laying",
        "Tower Climbing",
        "Antenna Alignment",
        "BTS Installation",
        "RF Planning",
        "RF Optimisation",
        "Drive Testing",
        "Network Troubleshooting",
        "Broadband Installation",
        "DTH Installation",
        "Router Configuration",
        "Modem Setup",
        "Last Mile Connectivity",
        "NOC Monitoring",
        "Fault Management",
        "SIM Activation"
    ],
    "energy": [
        "Line Maintenance",
        "Transformer Installation",
        "Substation Operation",
        "Switchyard Operation",
        "HT/LT Line Work",
        "Meter Reading",
        "Meter Installation",
        "Energy Auditing",
        "Load Management",
        "Solar Panel Mounting",
        "Solar Inverter Installation",
        "Battery Maintenance",
        "Wind Turbine Maintenance",
        "Boiler Operation",
        "Turbine Operation",
        "Cooling Tower Maintenance",
        "Water Treatment",
        "Effluent Treatment",
        "Pipeline Maintenance",
        "Gas Leak Detection"
    ],
    "automotive": [
        "Engine Repair",
        "Engine Overhauling",
        "Diesel Engine Repair",
        "Petrol Engine Repair",
        "Transmission Repair",
        "Clutch Repair",
        "Brake Repair",
        "Suspension Work",
        "Steering Alignment",
        "Wheel Balancing",
        "Tyre Fitting",
        "Auto Electrical",
        "Battery Servicing",
        "AC Repair (Auto)",
        "Denting",
        "Auto Painting",
        "Buffing",
        "Vehicle Inspection",
        "Diagnostic Scanning",
        "OBD Scanning",
        "EV Battery Servicing",
        "EV Motor Repair",
        "Two-Wheeler Servicing",
        "Body Shop Operations",
        "Spare Parts Management",
        "Service Advisory",
        "Insurance Claim Processing"
    ],
    "pharma": [
        "GMP",
        "GLP",
        "cGMP Compliance",
        "Batch Manufacturing Record",
        "Quality Assurance",
        "Quality Control",
        "HPLC",
        "GC",
        "UV Spectroscopy",
        "Dissolution Testing",
        "Stability Studies",
        "Method Validation",
        "Analytical Method Development",
        "Microbiological Testing",
        "Sterility Testing",
        "Cleaning Validation",
        "Process Validation",
        "Equipment Qualification",
        "Regulatory Submission",
        "ANDA",
        "DMF",
        "Pharmacovigilance",
        "Clinical Research",
        "GCP",
        "Clinical Data Management",
        "Medical Writing",
        "Formulation Development",
        "Tablet Compression",
        "Granulation",
        "Coating",
        "Packaging (Pharma)"
    ],
    "ecommerce": [
        "Order Processing",
        "Catalogue Management",
        "Product Listing",
        "Content Moderation",
        "Seller Onboarding",
        "Marketplace Operations",
        "Amazon Seller Central",
        "Flipkart Seller Hub",
        "Inventory Sync",
        "Returns Processing",
        "Refund Processing",
        "Customer Support",
        "Chat Support",
        "Email Support",
        "Voice Process",
        "Escalation Handling",
        "Quality Monitoring",
        "Performance Marketing",
        "Conversion Optimisation",
        "A/B Testing",
        "Growth Hacking",
        "Retention Marketing"
    ],
    "legal": [
        "Legal Research",
        "Case Law Analysis",
        "Drafting Petitions",
        "Contract Drafting",
        "Contract Review",
        "Due Diligence",
        "Litigation Support",
        "Court Filing",
        "Client Counselling",
        "Compliance Management",
        "Corporate Governance",
        "Company Law",
        "Labour Law",
        "Property Law",
        "Criminal Law",
        "Civil Law",
        "Family Law",
        "Taxation Law",
        "IPR",
        "Trademark Filing",
        "Patent Drafting",
        "Arbitration",
        "Mediation",
        "Legal Documentation",
        "Notarisation",
        "Stenography",
        "Legal Transcription"
    ],
    "realestate": [
        "Property Sales",
        "Site Visits",
        "Client Presentation",
        "Lead Follow-up",
        "Property Valuation",
        "Rental Management",
        "Lease Agreements",
        "Title Verification",
        "RERA Compliance",
        "Land Survey",
        "Total Station Operation",
        "AutoCAD Drafting",
        "Revit",
        "SketchUp",
        "3ds Max",
        "STAAD Pro",
        "ETABS",
        "Primavera",
        "MS Project",
        "Quantity Surveying",
        "Estimation",
        "Billing (Construction)",
        "BOQ Preparation",
        "Site Supervision",
        "Project Scheduling",
        "Interior Designing",
        "Space Planning",
        "Vastu Consulting"
    ],
    "travel": [
        "Ticketing",
        "Amadeus",
        "Galileo",
        "Sabre",
        "Itinerary Planning",
        "Visa Processing",
        "Passport Assistance",
        "Tour Packaging",
        "Hotel Booking",
        "Cab Coordination",
        "Group Travel",
        "Customer Handling (Travel)",
        "Cabin Crew Service",
        "In-flight Safety",
        "Ground Handling",
        "Baggage Handling",
        "Check-in Operations",
        "Ramp Operations",
        "Load Control",
        "Aviation Security",
        "Tour Guiding",
        "Destination Knowledge"
    ],
    "government": [
        "File Noting",
        "Dak Handling",
        "RTI Handling",
        "Tender Processing",
        "Government Procurement",
        "Scheme Implementation",
        "Beneficiary Verification",
        "Field Survey",
        "Data Collection",
        "Record Keeping",
        "Public Grievance Handling",
        "Panchayat Administration",
        "Revenue Records",
        "Land Records",
        "Census Operations",
        "Election Duty",
        "Sanitation Supervision",
        "Public Health Awareness"
    ]
}

# Sectors that share a skill pool with another sector.
SKILL_ALIASES = {
    "daily_wage": "skilled_trades",
    "transport_rail": "logistics",
    "mining": "manufacturing",
    "textiles": "manufacturing",
    "food_processing": "manufacturing",
    "waste": "security",
    "sports_wellness": "beauty_events",
    "social": "education",
    "defence": "security",
    "research": "education",
    "veterinary": "agriculture",
    "religious": "beauty_events",
}


def skills_for_sector(key: str) -> list[str]:
    """Skills for one sector, falling back to an alias or the full list."""
    if not key:
        return ALL_SKILLS
    return SKILLS_BY_SECTOR.get(key) or SKILLS_BY_SECTOR.get(SKILL_ALIASES.get(key, ""), []) or ALL_SKILLS


ALL_SKILLS = sorted({s for group in SKILLS_BY_SECTOR.values() for s in group})
