/**
 * Country dial codes for the phone input.
 *
 * `length` is the national number length (digits AFTER the dial code) and is
 * what the phone field caps typing at, so an Indian number stops at 10 and a
 * UAE number at 9 instead of a generic 15-digit free-for-all.
 *
 * `flag` holds the emoji, but it is only a FALLBACK. Windows has no flag
 * glyphs, so Chrome on Windows renders these as bare letters ("LA" instead of
 * the Laos flag). The Flag component renders a real image and drops back to
 * this emoji only if that image can't load. See components/Flag.jsx.
 *
 * These are the common/mobile lengths. A handful of countries have variable
 * national lengths; where that is true the most common mobile length is used.
 */
export const COUNTRIES = [
  { iso: "AF", name: "Afghanistan", dial: "+93", length: 9, flag: "🇦🇫" },
  { iso: "AL", name: "Albania", dial: "+355", length: 9, flag: "🇦🇱" },
  { iso: "DZ", name: "Algeria", dial: "+213", length: 9, flag: "🇩🇿" },
  { iso: "AD", name: "Andorra", dial: "+376", length: 6, flag: "🇦🇩" },
  { iso: "AO", name: "Angola", dial: "+244", length: 9, flag: "🇦🇴" },
  { iso: "AG", name: "Antigua and Barbuda", dial: "+1268", length: 7, flag: "🇦🇬" },
  { iso: "AR", name: "Argentina", dial: "+54", length: 10, flag: "🇦🇷" },
  { iso: "AM", name: "Armenia", dial: "+374", length: 8, flag: "🇦🇲" },
  { iso: "AU", name: "Australia", dial: "+61", length: 9, flag: "🇦🇺" },
  { iso: "AT", name: "Austria", dial: "+43", length: 10, flag: "🇦🇹" },
  { iso: "AZ", name: "Azerbaijan", dial: "+994", length: 9, flag: "🇦🇿" },
  { iso: "BS", name: "Bahamas", dial: "+1242", length: 7, flag: "🇧🇸" },
  { iso: "BH", name: "Bahrain", dial: "+973", length: 8, flag: "🇧🇭" },
  { iso: "BD", name: "Bangladesh", dial: "+880", length: 10, flag: "🇧🇩" },
  { iso: "BB", name: "Barbados", dial: "+1246", length: 7, flag: "🇧🇧" },
  { iso: "BY", name: "Belarus", dial: "+375", length: 9, flag: "🇧🇾" },
  { iso: "BE", name: "Belgium", dial: "+32", length: 9, flag: "🇧🇪" },
  { iso: "BZ", name: "Belize", dial: "+501", length: 7, flag: "🇧🇿" },
  { iso: "BJ", name: "Benin", dial: "+229", length: 8, flag: "🇧🇯" },
  { iso: "BT", name: "Bhutan", dial: "+975", length: 8, flag: "🇧🇹" },
  { iso: "BO", name: "Bolivia", dial: "+591", length: 8, flag: "🇧🇴" },
  { iso: "BA", name: "Bosnia and Herzegovina", dial: "+387", length: 8, flag: "🇧🇦" },
  { iso: "BW", name: "Botswana", dial: "+267", length: 8, flag: "🇧🇼" },
  { iso: "BR", name: "Brazil", dial: "+55", length: 11, flag: "🇧🇷" },
  { iso: "BN", name: "Brunei", dial: "+673", length: 7, flag: "🇧🇳" },
  { iso: "BG", name: "Bulgaria", dial: "+359", length: 9, flag: "🇧🇬" },
  { iso: "BF", name: "Burkina Faso", dial: "+226", length: 8, flag: "🇧🇫" },
  { iso: "BI", name: "Burundi", dial: "+257", length: 8, flag: "🇧🇮" },
  { iso: "KH", name: "Cambodia", dial: "+855", length: 9, flag: "🇰🇭" },
  { iso: "CM", name: "Cameroon", dial: "+237", length: 9, flag: "🇨🇲" },
  { iso: "CA", name: "Canada", dial: "+1", length: 10, flag: "🇨🇦" },
  { iso: "CV", name: "Cape Verde", dial: "+238", length: 7, flag: "🇨🇻" },
  { iso: "CF", name: "Central African Republic", dial: "+236", length: 8, flag: "🇨🇫" },
  { iso: "TD", name: "Chad", dial: "+235", length: 8, flag: "🇹🇩" },
  { iso: "CL", name: "Chile", dial: "+56", length: 9, flag: "🇨🇱" },
  { iso: "CN", name: "China", dial: "+86", length: 11, flag: "🇨🇳" },
  { iso: "CO", name: "Colombia", dial: "+57", length: 10, flag: "🇨🇴" },
  { iso: "KM", name: "Comoros", dial: "+269", length: 7, flag: "🇰🇲" },
  { iso: "CG", name: "Congo", dial: "+242", length: 9, flag: "🇨🇬" },
  { iso: "CD", name: "Congo (DRC)", dial: "+243", length: 9, flag: "🇨🇩" },
  { iso: "CR", name: "Costa Rica", dial: "+506", length: 8, flag: "🇨🇷" },
  { iso: "CI", name: "Cote d'Ivoire", dial: "+225", length: 10, flag: "🇨🇮" },
  { iso: "HR", name: "Croatia", dial: "+385", length: 9, flag: "🇭🇷" },
  { iso: "CU", name: "Cuba", dial: "+53", length: 8, flag: "🇨🇺" },
  { iso: "CY", name: "Cyprus", dial: "+357", length: 8, flag: "🇨🇾" },
  { iso: "CZ", name: "Czechia", dial: "+420", length: 9, flag: "🇨🇿" },
  { iso: "DK", name: "Denmark", dial: "+45", length: 8, flag: "🇩🇰" },
  { iso: "DJ", name: "Djibouti", dial: "+253", length: 8, flag: "🇩🇯" },
  { iso: "DM", name: "Dominica", dial: "+1767", length: 7, flag: "🇩🇲" },
  { iso: "DO", name: "Dominican Republic", dial: "+1809", length: 7, flag: "🇩🇴" },
  { iso: "EC", name: "Ecuador", dial: "+593", length: 9, flag: "🇪🇨" },
  { iso: "EG", name: "Egypt", dial: "+20", length: 10, flag: "🇪🇬" },
  { iso: "SV", name: "El Salvador", dial: "+503", length: 8, flag: "🇸🇻" },
  { iso: "GQ", name: "Equatorial Guinea", dial: "+240", length: 9, flag: "🇬🇶" },
  { iso: "ER", name: "Eritrea", dial: "+291", length: 7, flag: "🇪🇷" },
  { iso: "EE", name: "Estonia", dial: "+372", length: 8, flag: "🇪🇪" },
  { iso: "SZ", name: "Eswatini", dial: "+268", length: 8, flag: "🇸🇿" },
  { iso: "ET", name: "Ethiopia", dial: "+251", length: 9, flag: "🇪🇹" },
  { iso: "FJ", name: "Fiji", dial: "+679", length: 7, flag: "🇫🇯" },
  { iso: "FI", name: "Finland", dial: "+358", length: 9, flag: "🇫🇮" },
  { iso: "FR", name: "France", dial: "+33", length: 9, flag: "🇫🇷" },
  { iso: "GA", name: "Gabon", dial: "+241", length: 8, flag: "🇬🇦" },
  { iso: "GM", name: "Gambia", dial: "+220", length: 7, flag: "🇬🇲" },
  { iso: "GE", name: "Georgia", dial: "+995", length: 9, flag: "🇬🇪" },
  { iso: "DE", name: "Germany", dial: "+49", length: 10, flag: "🇩🇪" },
  { iso: "GH", name: "Ghana", dial: "+233", length: 9, flag: "🇬🇭" },
  { iso: "GR", name: "Greece", dial: "+30", length: 10, flag: "🇬🇷" },
  { iso: "GD", name: "Grenada", dial: "+1473", length: 7, flag: "🇬🇩" },
  { iso: "GT", name: "Guatemala", dial: "+502", length: 8, flag: "🇬🇹" },
  { iso: "GN", name: "Guinea", dial: "+224", length: 9, flag: "🇬🇳" },
  { iso: "GW", name: "Guinea-Bissau", dial: "+245", length: 7, flag: "🇬🇼" },
  { iso: "GY", name: "Guyana", dial: "+592", length: 7, flag: "🇬🇾" },
  { iso: "HT", name: "Haiti", dial: "+509", length: 8, flag: "🇭🇹" },
  { iso: "HN", name: "Honduras", dial: "+504", length: 8, flag: "🇭🇳" },
  { iso: "HK", name: "Hong Kong", dial: "+852", length: 8, flag: "🇭🇰" },
  { iso: "HU", name: "Hungary", dial: "+36", length: 9, flag: "🇭🇺" },
  { iso: "IS", name: "Iceland", dial: "+354", length: 7, flag: "🇮🇸" },
  { iso: "IN", name: "India", dial: "+91", length: 10, flag: "🇮🇳" },
  { iso: "ID", name: "Indonesia", dial: "+62", length: 10, flag: "🇮🇩" },
  { iso: "IR", name: "Iran", dial: "+98", length: 10, flag: "🇮🇷" },
  { iso: "IQ", name: "Iraq", dial: "+964", length: 10, flag: "🇮🇶" },
  { iso: "IE", name: "Ireland", dial: "+353", length: 9, flag: "🇮🇪" },
  { iso: "IL", name: "Israel", dial: "+972", length: 9, flag: "🇮🇱" },
  { iso: "IT", name: "Italy", dial: "+39", length: 10, flag: "🇮🇹" },
  { iso: "JM", name: "Jamaica", dial: "+1876", length: 7, flag: "🇯🇲" },
  { iso: "JP", name: "Japan", dial: "+81", length: 10, flag: "🇯🇵" },
  { iso: "JO", name: "Jordan", dial: "+962", length: 9, flag: "🇯🇴" },
  { iso: "KZ", name: "Kazakhstan", dial: "+7", length: 10, flag: "🇰🇿" },
  { iso: "KE", name: "Kenya", dial: "+254", length: 9, flag: "🇰🇪" },
  { iso: "KI", name: "Kiribati", dial: "+686", length: 8, flag: "🇰🇮" },
  { iso: "KW", name: "Kuwait", dial: "+965", length: 8, flag: "🇰🇼" },
  { iso: "KG", name: "Kyrgyzstan", dial: "+996", length: 9, flag: "🇰🇬" },
  { iso: "LA", name: "Laos", dial: "+856", length: 9, flag: "🇱🇦" },
  { iso: "LV", name: "Latvia", dial: "+371", length: 8, flag: "🇱🇻" },
  { iso: "LB", name: "Lebanon", dial: "+961", length: 8, flag: "🇱🇧" },
  { iso: "LS", name: "Lesotho", dial: "+266", length: 8, flag: "🇱🇸" },
  { iso: "LR", name: "Liberia", dial: "+231", length: 8, flag: "🇱🇷" },
  { iso: "LY", name: "Libya", dial: "+218", length: 9, flag: "🇱🇾" },
  { iso: "LI", name: "Liechtenstein", dial: "+423", length: 7, flag: "🇱🇮" },
  { iso: "LT", name: "Lithuania", dial: "+370", length: 8, flag: "🇱🇹" },
  { iso: "LU", name: "Luxembourg", dial: "+352", length: 9, flag: "🇱🇺" },
  { iso: "MO", name: "Macau", dial: "+853", length: 8, flag: "🇲🇴" },
  { iso: "MG", name: "Madagascar", dial: "+261", length: 9, flag: "🇲🇬" },
  { iso: "MW", name: "Malawi", dial: "+265", length: 9, flag: "🇲🇼" },
  { iso: "MY", name: "Malaysia", dial: "+60", length: 9, flag: "🇲🇾" },
  { iso: "MV", name: "Maldives", dial: "+960", length: 7, flag: "🇲🇻" },
  { iso: "ML", name: "Mali", dial: "+223", length: 8, flag: "🇲🇱" },
  { iso: "MT", name: "Malta", dial: "+356", length: 8, flag: "🇲🇹" },
  { iso: "MH", name: "Marshall Islands", dial: "+692", length: 7, flag: "🇲🇭" },
  { iso: "MR", name: "Mauritania", dial: "+222", length: 8, flag: "🇲🇷" },
  { iso: "MU", name: "Mauritius", dial: "+230", length: 8, flag: "🇲🇺" },
  { iso: "MX", name: "Mexico", dial: "+52", length: 10, flag: "🇲🇽" },
  { iso: "FM", name: "Micronesia", dial: "+691", length: 7, flag: "🇫🇲" },
  { iso: "MD", name: "Moldova", dial: "+373", length: 8, flag: "🇲🇩" },
  { iso: "MC", name: "Monaco", dial: "+377", length: 8, flag: "🇲🇨" },
  { iso: "MN", name: "Mongolia", dial: "+976", length: 8, flag: "🇲🇳" },
  { iso: "ME", name: "Montenegro", dial: "+382", length: 8, flag: "🇲🇪" },
  { iso: "MA", name: "Morocco", dial: "+212", length: 9, flag: "🇲🇦" },
  { iso: "MZ", name: "Mozambique", dial: "+258", length: 9, flag: "🇲🇿" },
  { iso: "MM", name: "Myanmar", dial: "+95", length: 9, flag: "🇲🇲" },
  { iso: "NA", name: "Namibia", dial: "+264", length: 9, flag: "🇳🇦" },
  { iso: "NR", name: "Nauru", dial: "+674", length: 7, flag: "🇳🇷" },
  { iso: "NP", name: "Nepal", dial: "+977", length: 10, flag: "🇳🇵" },
  { iso: "NL", name: "Netherlands", dial: "+31", length: 9, flag: "🇳🇱" },
  { iso: "NZ", name: "New Zealand", dial: "+64", length: 9, flag: "🇳🇿" },
  { iso: "NI", name: "Nicaragua", dial: "+505", length: 8, flag: "🇳🇮" },
  { iso: "NE", name: "Niger", dial: "+227", length: 8, flag: "🇳🇪" },
  { iso: "NG", name: "Nigeria", dial: "+234", length: 10, flag: "🇳🇬" },
  { iso: "KP", name: "North Korea", dial: "+850", length: 9, flag: "🇰🇵" },
  { iso: "MK", name: "North Macedonia", dial: "+389", length: 8, flag: "🇲🇰" },
  { iso: "NO", name: "Norway", dial: "+47", length: 8, flag: "🇳🇴" },
  { iso: "OM", name: "Oman", dial: "+968", length: 8, flag: "🇴🇲" },
  { iso: "PK", name: "Pakistan", dial: "+92", length: 10, flag: "🇵🇰" },
  { iso: "PW", name: "Palau", dial: "+680", length: 7, flag: "🇵🇼" },
  { iso: "PS", name: "Palestine", dial: "+970", length: 9, flag: "🇵🇸" },
  { iso: "PA", name: "Panama", dial: "+507", length: 8, flag: "🇵🇦" },
  { iso: "PG", name: "Papua New Guinea", dial: "+675", length: 8, flag: "🇵🇬" },
  { iso: "PY", name: "Paraguay", dial: "+595", length: 9, flag: "🇵🇾" },
  { iso: "PE", name: "Peru", dial: "+51", length: 9, flag: "🇵🇪" },
  { iso: "PH", name: "Philippines", dial: "+63", length: 10, flag: "🇵🇭" },
  { iso: "PL", name: "Poland", dial: "+48", length: 9, flag: "🇵🇱" },
  { iso: "PT", name: "Portugal", dial: "+351", length: 9, flag: "🇵🇹" },
  { iso: "QA", name: "Qatar", dial: "+974", length: 8, flag: "🇶🇦" },
  { iso: "RO", name: "Romania", dial: "+40", length: 9, flag: "🇷🇴" },
  { iso: "RU", name: "Russia", dial: "+7", length: 10, flag: "🇷🇺" },
  { iso: "RW", name: "Rwanda", dial: "+250", length: 9, flag: "🇷🇼" },
  { iso: "KN", name: "Saint Kitts and Nevis", dial: "+1869", length: 7, flag: "🇰🇳" },
  { iso: "LC", name: "Saint Lucia", dial: "+1758", length: 7, flag: "🇱🇨" },
  { iso: "VC", name: "Saint Vincent and the Grenadines", dial: "+1784", length: 7, flag: "🇻🇨" },
  { iso: "WS", name: "Samoa", dial: "+685", length: 7, flag: "🇼🇸" },
  { iso: "SM", name: "San Marino", dial: "+378", length: 10, flag: "🇸🇲" },
  { iso: "ST", name: "Sao Tome and Principe", dial: "+239", length: 7, flag: "🇸🇹" },
  { iso: "SA", name: "Saudi Arabia", dial: "+966", length: 9, flag: "🇸🇦" },
  { iso: "SN", name: "Senegal", dial: "+221", length: 9, flag: "🇸🇳" },
  { iso: "RS", name: "Serbia", dial: "+381", length: 9, flag: "🇷🇸" },
  { iso: "SC", name: "Seychelles", dial: "+248", length: 7, flag: "🇸🇨" },
  { iso: "SL", name: "Sierra Leone", dial: "+232", length: 8, flag: "🇸🇱" },
  { iso: "SG", name: "Singapore", dial: "+65", length: 8, flag: "🇸🇬" },
  { iso: "SK", name: "Slovakia", dial: "+421", length: 9, flag: "🇸🇰" },
  { iso: "SI", name: "Slovenia", dial: "+386", length: 8, flag: "🇸🇮" },
  { iso: "SB", name: "Solomon Islands", dial: "+677", length: 7, flag: "🇸🇧" },
  { iso: "SO", name: "Somalia", dial: "+252", length: 8, flag: "🇸🇴" },
  { iso: "ZA", name: "South Africa", dial: "+27", length: 9, flag: "🇿🇦" },
  { iso: "KR", name: "South Korea", dial: "+82", length: 10, flag: "🇰🇷" },
  { iso: "SS", name: "South Sudan", dial: "+211", length: 9, flag: "🇸🇸" },
  { iso: "ES", name: "Spain", dial: "+34", length: 9, flag: "🇪🇸" },
  { iso: "LK", name: "Sri Lanka", dial: "+94", length: 9, flag: "🇱🇰" },
  { iso: "SD", name: "Sudan", dial: "+249", length: 9, flag: "🇸🇩" },
  { iso: "SR", name: "Suriname", dial: "+597", length: 7, flag: "🇸🇷" },
  { iso: "SE", name: "Sweden", dial: "+46", length: 9, flag: "🇸🇪" },
  { iso: "CH", name: "Switzerland", dial: "+41", length: 9, flag: "🇨🇭" },
  { iso: "SY", name: "Syria", dial: "+963", length: 9, flag: "🇸🇾" },
  { iso: "TW", name: "Taiwan", dial: "+886", length: 9, flag: "🇹🇼" },
  { iso: "TJ", name: "Tajikistan", dial: "+992", length: 9, flag: "🇹🇯" },
  { iso: "TZ", name: "Tanzania", dial: "+255", length: 9, flag: "🇹🇿" },
  { iso: "TH", name: "Thailand", dial: "+66", length: 9, flag: "🇹🇭" },
  { iso: "TL", name: "Timor-Leste", dial: "+670", length: 8, flag: "🇹🇱" },
  { iso: "TG", name: "Togo", dial: "+228", length: 8, flag: "🇹🇬" },
  { iso: "TO", name: "Tonga", dial: "+676", length: 7, flag: "🇹🇴" },
  { iso: "TT", name: "Trinidad and Tobago", dial: "+1868", length: 7, flag: "🇹🇹" },
  { iso: "TN", name: "Tunisia", dial: "+216", length: 8, flag: "🇹🇳" },
  { iso: "TR", name: "Turkiye", dial: "+90", length: 10, flag: "🇹🇷" },
  { iso: "TM", name: "Turkmenistan", dial: "+993", length: 8, flag: "🇹🇲" },
  { iso: "TV", name: "Tuvalu", dial: "+688", length: 7, flag: "🇹🇻" },
  { iso: "UG", name: "Uganda", dial: "+256", length: 9, flag: "🇺🇬" },
  { iso: "UA", name: "Ukraine", dial: "+380", length: 9, flag: "🇺🇦" },
  { iso: "AE", name: "United Arab Emirates", dial: "+971", length: 9, flag: "🇦🇪" },
  { iso: "GB", name: "United Kingdom", dial: "+44", length: 10, flag: "🇬🇧" },
  { iso: "US", name: "United States", dial: "+1", length: 10, flag: "🇺🇸" },
  { iso: "UY", name: "Uruguay", dial: "+598", length: 8, flag: "🇺🇾" },
  { iso: "UZ", name: "Uzbekistan", dial: "+998", length: 9, flag: "🇺🇿" },
  { iso: "VU", name: "Vanuatu", dial: "+678", length: 7, flag: "🇻🇺" },
  { iso: "VA", name: "Vatican City", dial: "+379", length: 10, flag: "🇻🇦" },
  { iso: "VE", name: "Venezuela", dial: "+58", length: 10, flag: "🇻🇪" },
  { iso: "VN", name: "Vietnam", dial: "+84", length: 9, flag: "🇻🇳" },
  { iso: "YE", name: "Yemen", dial: "+967", length: 9, flag: "🇾🇪" },
  { iso: "ZM", name: "Zambia", dial: "+260", length: 9, flag: "🇿🇲" },
  { iso: "ZW", name: "Zimbabwe", dial: "+263", length: 9, flag: "🇿🇼" },
];

export const DEFAULT_ISO = "IN";

const BY_ISO = Object.fromEntries(COUNTRIES.map((c) => [c.iso, c]));
export const findCountry = (iso) => BY_ISO[iso];
